/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const reverse_string: (a: number, b: number) => [number, number];
export const quick_sort: (a: number, b: number) => [number, number];
export const fibonacci: (a: number) => bigint;
export const simple_hash: (a: number, b: number) => [number, number];
export const grayscale_image: (a: number, b: number) => [number, number];
export const binary_search: (a: number, b: number, c: number) => number;
export const levenshtein_distance: (a: number, b: number, c: number, d: number) => number;
export const is_prime: (a: bigint) => number;
export const unique_array: (a: number, b: number) => [number, number];
export const matrix_multiply: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const fast_power: (a: number, b: number) => number;
export const base64_encode: (a: number, b: number) => [number, number];
export const __wbg_arraystats_free: (a: number, b: number) => void;
export const __wbg_get_arraystats_mean: (a: number) => number;
export const __wbg_set_arraystats_mean: (a: number, b: number) => void;
export const __wbg_get_arraystats_median: (a: number) => number;
export const __wbg_set_arraystats_median: (a: number, b: number) => void;
export const __wbg_get_arraystats_std_dev: (a: number) => number;
export const __wbg_set_arraystats_std_dev: (a: number, b: number) => void;
export const __wbg_get_arraystats_min: (a: number) => number;
export const __wbg_set_arraystats_min: (a: number, b: number) => void;
export const __wbg_get_arraystats_max: (a: number) => number;
export const __wbg_set_arraystats_max: (a: number, b: number) => void;
export const array_statistics: (a: number, b: number) => number;
export const compress_string: (a: number, b: number) => [number, number];
export const validate_json: (a: number, b: number) => number;
export const moving_average: (a: number, b: number, c: number) => [number, number];
export const gcd: (a: bigint, b: bigint) => bigint;
export const lcm: (a: bigint, b: bigint) => bigint;
export const pascal_triangle: (a: number) => [number, number];
export const text_similarity: (a: number, b: number, c: number, d: number) => number;
export const main: () => void;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
